version: '3.9'

services:
  php-apache:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:oraclelinux8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - 3310:3306
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password

volumes:
  mysql-data:
    driver: local
